Repository rcpch/national-paediatric-diabetes-audit, pull requests merged in 2025-03, with the labels that each got.

#732 duplicate-nhs-number-same-submission
  project/npda/context_processors.py
  project/npda/forms/patient_form.py
  project/npda/general_functions/csv/csv_upload.py
  project/npda/kpi_class/kpis.py
  project/npda/models/patient.py
  project/npda/templates/npda/patient_form.html
  project/npda/templates/npda/visit_form.html
  project/npda/templates/partials/patient_table.html
  project/npda/templates/partials/patient_table_tips.html
  project/npda/templates/partials/visit_list_tips.html
  project/npda/templates/visits.html
  project/npda/templatetags/npda_tags.py
  project/npda/tests/form_tests/test_patient_form.py
  project/npda/tests/model_tests/test_submissions.py
  project/npda/tests/permissions_tests/test_patient_model_actions.py
  project/npda/views/patient.py
  project/npda/views/visit.py
  requirements/requirements.txt
  static/css/styles.css
  static/tailwind.css
Labels: refactor

#806 Fix column headers for age breakdown
  project/npda/templates/dashboard/components/cards/card_partials/patient_ages_partial.html
Labels: dashboard, LIVE - Royal Preston

#807 Fix patients with error counts in dashboard
  project/npda/views/dashboard/patient_measurements.py
Labels: dashboard, LIVE - Royal Preston

#814 Fix KPI 24 calculations for patients who no longer use HCL in their most recent visit
  project/npda/kpi_class/kpis.py
  project/npda/tests/kpi_calculations/test_kpis_24.py
Labels: LIVE - Royal Preston

#851 Fix dashboard crash changing audit year
  project/npda/views/home.py
Labels: LIVE - Royal Alexandra
